シーンのコンフィグ機能とサイズテンプレート
s10akir/cocktail pull request #21
Opened 2019-07-16 12:44 UTC by W-Tsutsumi

シーンのコンフィグ等に関連する機能です。
- シーン名やサイズを設定
- サイズのテンプレート用モデル
- シーンとサイズテンプレートからデータ取得

レビューよろしくお願いいたします。

2019-07-17 08:16 UTC, s10akir requested changes
フロントエンドに関する部分は機能的な間に合せなのでレビュー対象外としました。

2019-07-17 08:16 UTC, s10akir commented on src/scene/forms.py
> +                               help_text='シーンサイズの横の大きさを入力してください')
横の大きさ より 幅 のがよいのでは

2019-07-17 08:16 UTC, s10akir commented on src/scene/forms.py
> +                                help_text='シーンサイズの縦の大きさを入力してください')
縦の大きさ より 高さ のほうがよいのでは

2019-07-17 08:16 UTC, s10akir commented on src/scene/forms.py
> +                               help_text='シーンサイズの横の大きさを入力してください')
あとシーンサイズのサイズを指定するの頭の頭痛が痛い

2019-07-17 08:16 UTC, s10akir commented on src/scene/models.py
> +from django.db import models
モデル分割してる以上このスクリプトはいらないので削除しちゃってください

2019-07-17 08:16 UTC, s10akir commented on src/scene/models/scene.py
> +        '''
コメントの記法どちらかに統一してルール化してください
e.g. 全コメント`#`で, 一行コメントは`#`で&複数行コメントは`'''`で, 全コメント`'''`で など

2019-07-17 08:16 UTC, s10akir commented on src/scene/models/size_template.py
> +    def get_size_templates(self):
`SizeTemplate::get_size_templates()`冗長では？（SizeTemplateモデルにそれ以外のものが入ってるはずないのでget_allとかでよくない？）

2019-07-17 08:16 UTC, s10akir commented on src/scene/models/size_template.py
> +    def get_size_templates(self):
というかこのラッパー関数いらないのでは？

2019-07-17 08:16 UTC, s10akir commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
使いみちが謎（使いみちがあるとしてSceneモデルが持ってるべきふるまいではない）

2019-07-17 08:16 UTC, s10akir commented on src/scene/models/scene.py
> +        '''
↑このファイルについてではなく全体について

2019-07-17 14:30 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
UUIDをキーにしてモデルからデータを持ってくるとき、文字列がUUIDの形式になっていないと例外が発生するため。
クエリ文字列としてシーンIDを渡していたため、誤操作でのIDが書き換わってしまうこともあるのではと実装しました。
実装するのであれば、Sceneモデルが持つものではないため、プロジェクトファイル直下にtools.pyなどを作って置く感じでいいでしょうか。(他アプリから使われる可能性がありそうなので)

UUIDは人がいじらないものだとするのであれば、この関数は削除します。

![uuid_exception](https://user-images.githubusercontent.com/48192493/61383756-42521500-a8ea-11e9-9b4a-a2ff6f7e5636.png)

2019-07-17 14:30 UTC, W-Tsutsumi commented on src/scene/models/size_template.py
> +    def get_size_templates(self):
モデルからデータを持ってくるものだったのでモデルに実装したのですが、views.pyで`インスタンス.objects.all()`と持ってくる感じで大丈夫でしょうか

2019-07-17 14:45 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +        '''
ここはドキュメンテーションコメントを少し意識しました。
ただ、ドキュメンテーションコメントの書き方等はまだ決められていなかったと思うので、現時点では統一したほうがいいでしょうか。

2019-07-17 15:49 UTC, s10akir commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
UUIDが誤操作で書き換わること自体が不味くない？

2019-07-17 15:53 UTC, s10akir commented on src/scene/models/scene.py
> +        '''
ドキュメンテーションコメントにするのであればきっちりドキュメンテーションしてください。多分docstringでいきます。

2019-07-17 15:55 UTC, s10akir commented on src/scene/models/size_template.py
> +    def get_size_templates(self):
それ以上の処理がないのであればラッパーにするだけ無駄です むしろ同じ仕事をするインターフェースが分散するのは問題です

2019-07-17 15:56 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
すみません、誤操作ではないです。
今回はシーンIDをURLのクエリ文字列で渡していたため、そこを書き換えられてしまう可能性があるのではないかと思い実装しました。

2019-07-17 16:17 UTC, s10akir approved these changes

2019-07-17 16:17 UTC, s10akir commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
でもこれ結局例外握りつぶしてるだけでは？
* 再利用性がないのでメソッド切り出す必要がない
* 例外発生時べつに何かちゃんと処理をしてるわけではない

この辺考えてみてください

2019-07-17 16:18 UTC, s10akir requested changes
間違えてApproveしてしまった..

2019-07-17 16:18 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +        '''
了解です。
PEP257を参考に書き直します。

2019-07-17 16:21 UTC, W-Tsutsumi commented on src/scene/models/size_template.py
> +    def get_size_templates(self):
なるほど、了解です。
修正します。

2019-07-17 16:28 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +    def validate_uuid4(self, string):
了解です。
例外時のエラー処理などについて再考します。

2019-07-19 09:28 UTC, s10akir commented on src/scene/models/scene.py
> +    def set_user_id(self, user):
再利用性があるのでset_なんちゃらを一括でやるメソッドあっても良いかなと思うけどとりあえず今回はいいです

2019-07-19 09:31 UTC, s10akir requested changes

2019-07-19 09:31 UTC, s10akir commented on src/scene/models/scene.py
> +        """
コメントの件は？

2019-07-19 09:59 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +        """
pep257を参考にドキュメンテーションコメントとして書いたつもりです。
書き方が違うなどあれば、今回は全コメント`#`に統一してpushしなおします。

2019-07-19 10:02 UTC, s10akir commented on src/scene/models/scene.py
> +        """
https://github.com/s10akir/cocktail/pull/21#discussion_r304269813
"統一して" <= 統一されとらんが

2019-07-19 10:05 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +        """
ドキュメンテーションコメントとして書き直したつもりだったのですが...
ひとまず今回は統一し、今からpushします。

2019-07-19 10:08 UTC, s10akir commented on src/scene/models/scene.py
> +        """
上の方ドキュメントとしての体なしてなくないです？そんなことない？

2019-07-19 10:12 UTC, W-Tsutsumi commented on src/scene/models/scene.py
> +        """
確かにただのコメント感がありますね。
ドキュメントについてもう少し勉強します。
今回は統一します。

2019-07-20 14:58 UTC, s10akir approved these changes

2019-07-20 14:58 UTC, merged