個人名とEmailの変更を行う処理の分割
s10akir/cocktail pull request #22
Opened 2019-07-16 16:42 UTC by hknt3301

個人名とEmailを同時にしか変更できなかったので処理を分割しました。
レビューお願いします。

2019-07-16 18:24 UTC, tatikaze requested changes
基本的に良いと思います

2019-07-16 18:24 UTC, tatikaze commented on src/user/forms.py
> +        self.instance.update_name(name)
細かいかと思いますがメソッド内での変数の処理順番がまちまちなので統一したほうが見やすいと思います

2019-07-17 10:59 UTC, tatikaze approved these changes
問題なさそうです

2019-07-17 15:48 UTC, s10akir commented
時間に余裕が無いのでマージするが後々関数定義順リファクタリング

2019-07-17 15:48 UTC, merged