パスワード認証の項目の追加
s10akir/cocktail pull request #25
Opened 2019-07-18 06:37 UTC by hknt3301

パスワード認証関連の機能です。
- パスワード認証を行う機能のメソッドの追加。
- 情報変更ページにパスワード認証項目を追加。

レビューお願いします。

2019-07-18 16:41 UTC, tatikaze requested changes
確認しました。
一点だけ確認お願いします

2019-07-18 16:41 UTC, tatikaze commented on src/user/models/user.py
> +    def password_auth(self, raw_password):
メソッド名は動詞から始めた方が自然では？
auth_passwordとか
他でメソッドが呼ばれてるようなら変更なしでよいと思います

2019-07-18 16:57 UTC, tatikaze requested changes

2019-07-18 16:57 UTC, tatikaze commented on src/user/forms.py
> +        help_text='情報を変更するためにはパスワードを入力してください'
日本語として適切でないのでは？

2019-07-18 17:34 UTC, tatikaze approved these changes
確認しました
良いと思います

2019-07-19 09:37 UTC, s10akir requested changes

2019-07-19 09:37 UTC, s10akir commented on src/user/models/user.py
> +
これわざわざラッパー関数作ってる理由を教えてください
(before_password_validatorについても)

2019-07-19 12:48 UTC, hknt3301 commented on src/user/models/user.py
> +
DBに保存されいる項目との比較のためにmodelに作りました。指摘されて気づいたのですがラッパー関数として意味がない状態だと思いましたので修正します。

2019-07-20 15:06 UTC, s10akir requested changes

2019-07-20 15:06 UTC, s10akir commented on src/user/models/user.py
> -
必要な作業内容と違うコミットを混ぜないでください。
既存機能の変更についてはデグレが発生する可能性があるので、またロールバックする際の影響スコープが明確にならないので、その際に行うべき作業とそうでないものを混同するなということは度々説明しています。

2019-08-18 12:41 UTC, s10akir approved these changes

2019-08-18 13:27 UTC, tatikaze requested changes
確認おねがいします

2019-08-18 13:27 UTC, tatikaze commented on src/user/forms.py
> +            )
")"の位置について、上部（71～75）で行ったメソッド追加に習うのであればインデントが一つ足りないのでは？

2019-08-18 13:29 UTC, tatikaze commented
コミットメッセージに関して、"指摘事項の修正"などでは実際にどんな変更が行われているか分からないため、実際に行った変更や変更に対する理由などを書くようにしてください

2019-08-19 06:23 UTC, hknt3301 commented on src/user/forms.py
> +            )
")"は39行目~41行目と43行目～45行目に倣ってこの位置にしました。

2019-08-19 07:23 UTC, tatikaze approved these changes

2019-08-19 07:23 UTC, tatikaze commented on src/user/forms.py
> +            )
一旦了解です。リファクタリングの時にまた確認しましょう

2019-08-19 07:33 UTC, merged